apiVersion: v1
kind: LimitRange
metadata:
  name: manual-managed-limits
  namespace: manual-managed
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1"
        memory: 512Mi