apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: manual-managed
  labels:
    app: podinfo
spec:
  selector:
    app: podinfo
  ports:
    # label above + this port name are both needed by the servicemonitor
    - name: http
      port: 9898
      targetPort: http
  type: ClusterIP